version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www/html
        depends_on:
            - db
        networks:
            - laravel
        environment:
            - MYSQL_ROOT_PASSWORD= 123456
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel_1
            - DB_USERNAME=laravel_1
            - DB_PASSWORD=123456
        volumes:
            - ./:/var/www/html

    webserver:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel_1
            MYSQL_USER: laravel_1
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
